name: traktor_family_gastro_bar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  flutter_bloc: ^8.1.4
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/images/
  fonts:
    - family: OpenSans
      fonts: 
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true