name: traktor_family_gastro_bar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  connectivity_plus: ^6.0.3
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  url_launcher: ^6.2.4
  provider: ^6.1.2
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  firebase_messaging: ^14.9.2
  firebase_auth: ^4.20.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: OpenSans
      fonts: 
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true