// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzlVWAXUTnDIhENFrTAJspYOw-pOiXBnM',
    appId: '1:907812321603:android:1f28bb445a7ee70e8197f6',
    messagingSenderId: '907812321603',
    projectId: 'traktor-family-gastro-bar',
    databaseURL: 'https://traktor-family-gastro-bar-default-rtdb.firebaseio.com',
    storageBucket: 'traktor-family-gastro-bar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN-c8p82R7JBJFddrBPzY_XeeMncPP948',
    appId: '1:907812321603:ios:9502620570cefef48197f6',
    messagingSenderId: '907812321603',
    projectId: 'traktor-family-gastro-bar',
    databaseURL: 'https://traktor-family-gastro-bar-default-rtdb.firebaseio.com',
    storageBucket: 'traktor-family-gastro-bar.appspot.com',
    iosBundleId: 'com.example.traktorFamilyGastroBar',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8MUrPiS-kPbqMAHwgDI_3q22At578oNI',
    appId: '1:907812321603:web:9cdea74d1e2eaa0f8197f6',
    messagingSenderId: '907812321603',
    projectId: 'traktor-family-gastro-bar',
    authDomain: 'traktor-family-gastro-bar.firebaseapp.com',
    databaseURL: 'https://traktor-family-gastro-bar-default-rtdb.firebaseio.com',
    storageBucket: 'traktor-family-gastro-bar.appspot.com',
    measurementId: 'G-S1RTN99YKL',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8MUrPiS-kPbqMAHwgDI_3q22At578oNI',
    appId: '1:907812321603:web:07ef12a0961fe1f88197f6',
    messagingSenderId: '907812321603',
    projectId: 'traktor-family-gastro-bar',
    authDomain: 'traktor-family-gastro-bar.firebaseapp.com',
    databaseURL: 'https://traktor-family-gastro-bar-default-rtdb.firebaseio.com',
    storageBucket: 'traktor-family-gastro-bar.appspot.com',
    measurementId: 'G-HB7MCFVGHS',
  );

}